version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: vitorhugo/reverse-proxy 
  backend_user:
    build:
      context: ../udagram-restapi-user
    image: vitorhugo/udagram-restapi-user
  backend_feed:
    build:
      context: ../udagram-restapi-feed  
    image: vitorhugo/udagram-restapi-feed
  frontend:
    build:
      context: ../udagram-frontend  
    image: vitorhugo/udagram-frontend
